# Generated by Django 6.0.4 on 2026-04-13 04:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmotors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='xmotors.car'),
            preserve_default=False,
        ),
    ]
